version: '0.0'
services:
  python-gpt-db:
    container_name: python-gpt-db
    build: 
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data/
  python-gpt-app:
    container_name: python-gpt-app
    build: 
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - python-gpt-db
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: python-gpt-db
      DB_PORT: 5432
      PYTHONUNBUFFERED: 1
      USER_CODE_DIRECTORY: ${USER_CODE_DIRECTORY}
      FILES_STRUCTURE_FOLDER: ${FILES_STRUCTURE_FOLDER}
      NAMES_FILE: ${NAMES_FILE}
      RELATIONSHIPS_FILE: ${RELATIONSHIPS_FILE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RELATIVE_DIFF: 0.05
  python-gpt-st: 
    container_name: python-gpt-st
    build: 
      context: . 
      dockerfile: Dockerfile
    depends_on: 
      - python-gpt-app
      - python-gpt-db
    ports: 
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres: