version: '0.0'
services:
  python-gpt-db:
    container_name: python-gpt-db
    build: 
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data/
  python-gpt-st: 
    container_name: python-gpt-st
    build: 
      context: . 
      dockerfile: Dockerfile
    depends_on: 
      - python-gpt-db
    ports: 
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres: